Int_cent moeda na notação de centavos
pablogallardo/livrenfe pull request #13
Opened 2017-08-10 05:14 UTC by icaroraci

Este é todo o trabalho que fiz. Andei trabalhando duro nisso, mas realmente não comsigo mais compilar o projeto, o que me levou a ter que forçadamente parar.
Espero que seja util e possa aproveitar.

2017-08-10 23:04 UTC, pablogallardo requested changes
Muito obrigado @icaroraci pela ajuda em fazer esta mudança. Segue as mudanças que farão que o projeto compile e outros ajustes necessários. Também é bom executar `# make uninstall && make clean` e `$ make` por se ficou instalado algum header antigo no seu sistema.

Está fazendo um bom trabalho! Não testei ainda suas mudanças pois o trabalho não está terminado mas se vê bem.

2017-08-10 23:04 UTC, pablogallardo commented on src/db_nfe.c
> +		 '%d', '%d', '%d', '%s', '%d', %Q, %d, '%d' , '%d', %i, %Q,\
Prefira sempre `%d` antes que `%i`, desta forma, continuamos o padrão do projeto

2017-08-10 23:04 UTC, pablogallardo commented on src/item_manager.c
> +#include <libnfe/utils.h>
Esta linha tem que ser mudada para `"libnfe/utils.h"` pois este arquivo não está na pasta `include` do projeto

2017-08-10 23:04 UTC, pablogallardo commented on src/libnfe/utils.c
> +double aliquotatoduble(aliquota percentual){
O nome deve ser `aliquotatodouble` faltou a "o"

2017-08-10 23:04 UTC, pablogallardo commented on src/libnfe/utils.h
> +#include "libnfe/libnfe.h"
Esta linha deve ser `<libnfe/libnfe.h>` porque este arquivo pertence à pasta `include`

2017-08-10 23:04 UTC, pablogallardo commented on src/crypto_interface.c
> +	return 1;
Isto deve ser `return 0;`. O valor `0` significa que deu tudo certo.

2017-08-11 01:02 UTC, icaroraci commented
Obrigado Pablo pelas dicas.
Acertei os detalhes que me pediu.

2017-08-11 01:41 UTC, pablogallardo commented
Ótimo @icaroraci. E conseguiu compilar?

2017-08-19 02:01 UTC, closed without merging