Adicionado pkgbuild para Arch Linux e distros.
pablogallardo/livrenfe pull request #14
Opened 2017-08-22 07:38 UTC by gabrielmoura

Senti a necessidade de criar-lo para mim e decidi compartilhar com o criador.

2017-08-22 14:45 UTC, pablogallardo commented
Muito obrigado @gabrielmoura pelo patch! E bem-vindo ao desenvolvimento do projeto.

Testarei a instalação no meu Arch assim que puder e, se tudo ser certo, farei o merge.

Queria também te avisar que este projeto está em processo de junção com o projeto microsped (https://github.com/silvioprog/microsped) para se tornar um projeto mais completo e robusto. Em breve teremos novidades sobre esta mudança.

2017-08-25 02:25 UTC, pablogallardo requested changes
@gabrielmoura, bom trabalho e obrigado pelo patch. Segue só uma observação:

2017-08-25 02:25 UTC, pablogallardo commented on PKGBUILD
> +depends=('xml2' 'xmlsec' 'curl' 'openssl' 'sqlite' 'gtk3')
Na minha instalação de archlinux o pacman não consegue resolver o pacote `xml2`. Tive que trocar para `libxml2` e assim funcionou. Por favor, verifique se assim funciona na sua instalação também. Se funcionar, faça a mudança por favor.

2017-08-26 04:10 UTC, gabrielmoura commented on PKGBUILD
> +depends=('xml2' 'xmlsec' 'curl' 'openssl' 'sqlite' 'gtk3')
Se funcionou na sua instalação eu vou mudar aqui. O pacote que eu havia indicado é este [community/xml2](https://www.archlinux.org/packages/community/x86_64/xml2).
Vou alterar agora.

2017-08-26 19:13 UTC, pablogallardo approved these changes

2017-08-26 19:14 UTC, merged

2017-08-26 19:21 UTC, pablogallardo commented
@gabrielmoura, obrigado! Acabo de fazer o merge do patch.

Como te comentei, estamos fazendo uma junção deste projeto com outro para criar Pitangus (https://github.com/crossteam/pitangus). Vamos melhorar bastante esta ferramenta. Se quiser, pode me enviar um e-mail para pggllrd@gmail.com com sugestões para este emissor, características que você gostaria que tivesse ou se quiser participar do desenvolvimento (não é necessário ser um especialista em C).