Inclusao dos Enums para TAG <ide>
pablogallardo/livrenfe pull request #4
Opened 2017-06-28 03:23 UTC by icaroraci

Esse PR integra os Enums necessários para gerar a TAG <ide>.
Todos os Enums em libnfe.h para facilitar includes.

2017-06-29 01:13 UTC, pablogallardo requested changes
Muito obrigado Gabriel! Estes enums ficaram melhores que os anteriores.

Estava lendo alguns artigos, e aproveitando que vamos fazer esta alteração, podemos adotar a seguinte convenção para os typedef:

Usar:
typedef enum tipo_t{
// Elementos
} tipo;

Veja: http://www.montefiore.ulg.ac.be/~piater/Cours/Coding-Style/index.html#id2465262

Uma exceção a esta regra será mod, é uma palavra reservada, portanto podemos usar MOD.

2017-06-29 01:13 UTC, pablogallardo commented on include/libnfe/libnfe.h
> +typedef enum t_indPag {
Por favor, mude para indPag_t

2017-06-29 01:13 UTC, pablogallardo commented on include/libnfe/libnfe.h
> +}TE_INDPAG  ;
mudar para indPag

2017-06-29 01:13 UTC, pablogallardo commented on include/libnfe/libnfe.h
> + }TE_MOD;
Neste caso, mod é uma palavra reservada, como alternativa, podemos usar MOD (todo maiúsculas)

2017-06-29 01:13 UTC, pablogallardo commented on include/libnfe/libnfe.h
> +typedef enum t_tpNF{
Aplicar mesma convenção em todos os enums

2017-06-29 01:13 UTC, pablogallardo commented on include/libnfe/libnfe.h
> + * @Pablo
Boa ideia! Pode aplicar a mudança em todo o projeto. Pode ser neste PR ou  em outro posterior.

2017-06-29 01:13 UTC, pablogallardo commented on include/libnfe/libnfe.h
> +	TE_INDPAG  ind_pag;
Mudar para a convenção citada na definição

2017-06-29 01:13 UTC, pablogallardo commented on src/libnfe/enum.h
>  #ifndef ENUM_H
Este arquivo não será mais necessário pois os enums estão no libnfe.h.

2017-06-29 01:13 UTC, pablogallardo commented on include/libnfe/libnfe.h
> +	 NFe  = 55,
Como as palavras NFe e NFCe são muito usadas em projetos deste tipo. Por favor, troque para MOD_NFe e MOD_NFCe para deixar disponível estas palavras para qualquer outro emissor que deseje usar esta biblioteca.

2017-07-01 17:23 UTC, icaroraci commented on include/libnfe/libnfe.h
> + }TE_MOD;
Ou Mod só com o M maiusculo.

2017-07-01 17:35 UTC, icaroraci commented on include/libnfe/libnfe.h
> + * @Pablo
Em outro será melhor.

2017-07-01 19:51 UTC, pablogallardo commented on include/libnfe/libnfe.h
> + * @Pablo
Perfeito! Então, por favor, coloque o item no arquivo TODO e apaque este comentário.

2017-07-01 20:15 UTC, pablogallardo requested changes

2017-07-01 20:15 UTC, pablogallardo commented on include/libnfe/libnfe.h
> +/*
Excelente aporte ao projeto! A forma em como está organizado hoje o PAIS está totalmente fora de lugar. O que estava pensando é que conforme temos que atualizar todos os structs para se alinhar com o novo padrão de structs. Poderia aplicar as mudanças diretamente nos structs PAIS, MUNICIPIO, UF e ENDERECO? 

Em uma segunda instância fazemos a atualização dos structs ao novo padrão.

2017-07-01 20:20 UTC, pablogallardo commented
Gabriel, Excelente trabalho, vi que você fez as mudanças solicitadas. E elas já estão prontas para o merge. Só, conforme o comentário dos structs que tem a ver com o Endereco, faça a mudança diretamente no struct já existente. Mesmo sem se adaptar ao padrão. Desta maneira, você não terá tantas mudanças no código.

Inclusive, é melhor fazer outro PR só para a mudança do endereço. Pois as outras mudanças já estão aprovadas.

2017-07-02 20:07 UTC, pablogallardo approved these changes

2017-07-02 20:11 UTC, pablogallardo commented
Gabriel, conforme falamos, as mudanças foram aprovadas com exceção dos structs enderecos onde as mudanças serão aplicadas aos structs já existentes

2017-07-02 20:11 UTC, closed without merging